import HomeContainer from "../containers/HomeContainer";
// import styles from "../styles/Home.module.scss";
import { useState } from "react";
import Navbar from "../components/Navbar";
import Head from "next/head";

export default function Home() {
	const [menuShow, showMenu] = useState(false);

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar menuShow={menuShow} showMenu={showMenu} />
			<HomeContainer />
		</div>
	);
}
